server:
  port: 8081
tomcat:
  max-http-post-size: 8192

spring:
  profiles:
    # 外置jdbc、redis和mail配置文件
    active: jdbc,redis,mail
  # 关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  # 配置国际化资源文件
  messages:
    basename: i18n.logo
  main:
    allow-circular-references: true



#浏览器cookie相关设置
COOKIE:
  # 设置cookie默认时长为30分钟
  VALIDITY: 1800
